FROM bellsoft/liberica-openjdk-debian:21.0.1

# скопировать все файлы из локальной машины в app
COPY gateway/build/output-docker/gateway.jar /app/

# задать рабоч директорию
WORKDIR /app

ENTRYPOINT ["java", "--enable-preview", "-jar" ,"gateway.jar"]