spring:
  application:
    name: gw

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          core: TRACE

#  spring.servlet.multipart.max-file-size=10MB
#  spring.servlet.multipart.max-request-size=10MB

